#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) Enrico Weigelt, metux IT consult <info@metux.net>

set -e

TESTBED_NODE_NAME=librezimbra-test-ldap-m3
TESTBED_NODE_DOCKER_OPT="-p 2389:389"
TESTBED_NODE_TYPE="ldap-master"
TESTBED_NODE_ID="3"
TESTBED_LDAP_MASTERS="librezimbra-test-ldap-m1 librezimbra-test-ldap-m2 librezimbra-test-ldap-m3"
TESTBED_LDAP_REPLICATION_PASSWORD="knollo123"

. etc/testbed.sh

testbed_start_ldap
