#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) Enrico Weigelt, metux IT consult <info@metux.net>

WEBROOT=.aptrepo/default/ubuntu-focal-amd64
PORT="8090"

nohup python3 -m http.server $PORT --directory $WEBROOT >/dev/null &>/dev/null &
