#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) Enrico Weigelt, metux IT consult <info@metux.net>

# Start a test container. If no args given, just run a shell, otherwise
# run the args as command line inside the test container.

set -e

CONTAINER_IMAGE=librezimbra-test-ldap
CONTAINER_SHELL=/bin/bash
CONTAINER_HOSTNAME=librezimbra-test-ldap

MYSELF=$(readlink -f "$0")

WORK_DIR=$(dirname "$MYSELF")
SSH_DIR=$HOME/.ssh

( cd docker && make librezimbra-test-ldap )

if [ ! "$1" ]; then
    CMD="$CONTAINER_SHELL"
fi

docker run --privileged -it \
    --mount "src=$WORK_DIR,target=/home/build/src,type=bind" \
    --mount "src=$SSH_DIR,target=/home/build/.ssh,type=bind,ro" \
    --hostname "$CONTAINER_HOSTNAME" \
    -p 8000:8000 \
    $CONTAINER_IMAGE $CMD "$@"
