#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) Enrico Weigelt, metux IT consult <info@metux.net>

set -m

. /opt/zimbra/libexec/zm-mbox-util.sh

## fixme:

read_tag() {
    local tag="$1"
    if [ -f /conf/$tag ]; then
        cat /conf/$tag
    fi
}

copy_certs() {
#    zm_ldap_install_ca /conf/ca/*.pem
    zm_convert_p12_jks /conf/mailboxd.p12 $ZIMBRA_ROOT/jetty_base/etc/keystore
}

mk_ldap_url() {
    needspace=""
    while [ "$1" ]; do
        [ "$needspace" ] && echo -n " "
        echo -n "ldap://$1"
        needspace=1
        shift
    done
}

copy_certs

node_name=`read_tag node-name`
node_type=`read_tag node-type`

ldap_masters=`read_tag ldap-masters`
ldap_readonly=`read_tag ldap-readonly`

zm_log_info "ldap masters: $ldap_masters"
zm_log_info "ldap_readonly: $ldap_readonly"

if [ ! "$ldap_readonly" ]; then
    zm_log_info "no readonly ldap nodes specified. using masters"
    ldap_readonly="$ldap_masters"
fi

zm_localconfig_set ldap_master_url `mk_ldap_url $ldap_masters`
zm_localconfig_set ldap_url `mk_ldap_url $ldap_readonly`
zm_localconfig_set zimbra_server_hostname "$node_name"
zm_localconfig_set zimbra_ldap_password `read_tag ldap-zimbra-password`

# need to reload localconfig
. $ZIMBRA_ROOT/libexec/zm-load-localconfig.sh

# tempdir for jython
zm_init_datatmp
zm_mbox_createserver "$node_name"

/etc/init.d/rsyslog start

## fixme: move this to ldap package ?
zm_globalconf_set zimbraHttpNumThreads                     250
zm_globalconf_set zimbraHttpThreadPoolMaxIdleTimeMillis    10000
zm_globalconf_set zimbraIPMode                             ipv4
zm_globalconf_set zimbraMailPort                           8080  # zimbra is not runnng as root (otherwise 80)
zm_globalconf_set zimbraMailSSLPort                        8443
zm_globalconf_set zimbraLogToSyslog                        TRUE
zm_globalconf_set zimbraAdminURL                           "/zimbraAdmin"
zm_globalconf_set zimbraLmtpBindPort                       7025
zm_globalconf_set zimbraPop3ServerEnabled                  TRUE
zm_globalconf_set zimbraPop3BindPort                       7110
zm_globalconf_set zimbraPop3SSLServerEnabled               TRUE
zm_globalconf_set zimbraPop3SSLBindPort                    7995
zm_globalconf_set zimbraImapServerEnabled                  TRUE
zm_globalconf_set zimbraImapBindPort                       7143
zm_globalconf_set zimbraImapSSLServerEnabled               TRUE
zm_globalconf_set zimbraImapSSLBindPort                    7993
zm_globalconf_set zimbraSSLExcludeCipherSuites             ".*_RC4_.*"
zm_globalconf_set zimbraHttpConnectorMaxIdleTimeMillis     60000
zm_globalconf_set zimbraHttpOutputBufferSize               32768
zm_globalconf_set zimbraHttpRequestHeaderSize              8192
zm_globalconf_set zimbraHttpResponseHeaderSize             8192
zm_globalconf_set zimbraMailMode                           http
zm_globalconf_set zimbraMailboxdSSLRenegotiationAllowed    TRUE
zm_globalconf_set zimbraMtaAuthPort                        7073
zm_globalconf_set zimbraExtensionBindPort                  7072
zm_globalconf_set zimbraHttpHeaderCacheSize                512
zm_globalconf_set zimbraAdminPort                          7071
zm_globalconf_set zimbraDocumentEditingCallbackPort        7074

# autogenerated server attributes
#zimbraPop3BindAddress
#zimbraPop3SSLBindAddress
#zimbraImapBindAddress
#zimbraImapSSLBindAddress
#zimbraSSLExcludeCipherSuitesXML
#zimbraMailBindAddress
#zimbraMailSSLBindAddress

zm_localconfig_set mailboxd_keystore_password "$ZM_JKS_PASSWORD"

zm_log_info "running zmconfigd"
su - $ZIMBRA_USER -c $ZIMBRA_ROOT/libexec/zmconfigd-oneshot

echo "falling back to interactive shell"
cd /opt/zimbra

su - $ZIMBRA_USER -c /zm-jetty

bash
