# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) Enrico Weigelt, metux IT consult <info@metux.net>

. /opt/zimbra/libexec/zm-util-base.sh
. /opt/zimbra/libexec/zm-load-localconfig.sh

zm_ldapadd() {
    for url in $ldap_master_url ; do
        zm_log_info "$0: trying ldap master: $url"
        $ZM_LDAP_BINDIR/ldapadd -D "$zimbra_ldap_userdn" -w "$zimbra_ldap_password" -Q -H "$url" "$@"
        # fixme: check whether we reached him
        return $?
    done
}

zm_ldapsearch() {
    for url in $ldap_master_url ; do
        zm_log_info "$0: trying ldap master: $url"
        $ZM_LDAP_BINDIR/ldapsearch -D "$zimbra_ldap_userdn" -w "$zimbra_ldap_password" -H "$url" "$@"
        # fixme: check whether we reached him
        return $?
    done
}

zm_ldapmodify() {
    for url in $ldap_master_url ; do
        zm_log_info "$0: trying ldap master: $url"
        $ZM_LDAP_BINDIR/ldapmodify -D "$zimbra_ldap_userdn" -w "$zimbra_ldap_password" -H "$url" "$@"
        return $?
    done
}

zm_mbox_createserver() {
    local nodename="$1"
    zm_server_create "$nodename"
    zm_server_enable_service "$nodename" "mailbox"
    zm_server_enable_service "$nodename" "zimbra"
    zm_server_enable_service "$nodename" "service"
}

zm_mbox_mailboxd_init() {
    zm_localconfig_set mailboxd_keystore_password "$ZM_JKS_PASSWORD"
    zm_localconfig_set mailboxd_truststore /etc/ssl/certs/java/cacerts
}

zm_runas() {
    su - $ZIMBRA_USER -c "$@"
}

zm_zmconfigd_oneshot() {
    # tempdir for jython
    zm_init_datatmp
    zm_log_info "running zmconfigd (oneshot)"
    zm_runas $ZIMBRA_ROOT/libexec/zmconfigd-oneshot
}

zm_mbox_globalconf() {
    ## fixme: move this to ldap package ?
    zm_globalconf_set zimbraHttpNumThreads                     250
    zm_globalconf_set zimbraHttpThreadPoolMaxIdleTimeMillis    10000
    zm_globalconf_set zimbraIPMode                             ipv4
    zm_globalconf_set zimbraMailPort                           8080  # zimbra is not runnng as root (otherwise 80)
    zm_globalconf_set zimbraMailSSLPort                        8443
    zm_globalconf_set zimbraLogToSyslog                        TRUE
    zm_globalconf_set zimbraAdminURL                           "/zimbraAdmin"
    zm_globalconf_set zimbraLmtpBindPort                       7025
    zm_globalconf_set zimbraPop3ServerEnabled                  TRUE
    zm_globalconf_set zimbraPop3BindPort                       7110
    zm_globalconf_set zimbraPop3SSLServerEnabled               TRUE
    zm_globalconf_set zimbraPop3SSLBindPort                    7995
    zm_globalconf_set zimbraImapServerEnabled                  TRUE
    zm_globalconf_set zimbraImapBindPort                       7143
    zm_globalconf_set zimbraImapSSLServerEnabled               TRUE
    zm_globalconf_set zimbraImapSSLBindPort                    7993
    zm_globalconf_set zimbraSSLExcludeCipherSuites             ".*_RC4_.*"
    zm_globalconf_set zimbraHttpConnectorMaxIdleTimeMillis     60000
    zm_globalconf_set zimbraHttpOutputBufferSize               32768
    zm_globalconf_set zimbraHttpRequestHeaderSize              8192
    zm_globalconf_set zimbraHttpResponseHeaderSize             8192
    zm_globalconf_set zimbraMailMode                           http
    zm_globalconf_set zimbraMailboxdSSLRenegotiationAllowed    TRUE
    zm_globalconf_set zimbraMtaAuthPort                        7073
    zm_globalconf_set zimbraExtensionBindPort                  7072
    zm_globalconf_set zimbraHttpHeaderCacheSize                512
    zm_globalconf_set zimbraAdminPort                          7071
    zm_globalconf_set zimbraDocumentEditingCallbackPort        7074

    # autogenerated server attributes
    #zimbraPop3BindAddress
    #zimbraPop3SSLBindAddress
    #zimbraImapBindAddress
    #zimbraImapSSLBindAddress
    #zimbraSSLExcludeCipherSuitesXML
    #zimbraMailBindAddress
    #zimbraMailSSLBindAddress
}
