#!/bin/bash

. /opt/zimbra/libexec/zm-util-base.sh

[ "$ZM_MYSQL_DATADIR" ] || ZM_MYSQL_DATADIR="$ZIMBRA_ROOT/db/data"
[ "$ZM_MYSQL_SOCKET"  ] || ZM_MYSQL_SOCKET="$ZIMBRA_ROOT/data/tmp/mysql/mysql.sock"

if [ ! -d $ZM_MYSQL_DATADIR/mysql ]; then
    zm_log_info "need to initialize mysql database"
    /usr/bin/mysql_install_db \
        --defaults-file=$ZIMBRA_ROOT/conf/my.cnf \
        --datadir=$ZM_MYSQL_DATADIR \
        --user=zimbra
else
    zm_log_info "mysql already initialized"
fi

zm_mbox_mysql_start() {
    /usr/bin/mysqld_safe --defaults-file=/opt/zimbra/conf/my.cnf &

    count=0
    while [ $count -lt 100 ] ; do
        if /usr/bin/mysqladmin -c 10 --socket=$ZM_MYSQL_SOCKET ping ; then
            zm_log_info "mysql server started"
            return 0
        else
            zm_log_info "mysql not up yet"
            sleep 0.1
        fi
    done
    zm_log_err "time out. failed starting mysql"
    return 1
}

if ! zm_mbox_mysql_start ; then
    zm_log_err "terminating"
    exit 1
fi

zm_log_info "trying some ops"
echo "SELECT 1; " | mysql --socket=$ZM_MYSQL_SOCKET
