#!/bin/bash

export ZIMBRA_ROOT=/opt/zimbra

[ "$ZM_MYSQL_DATADIR" ] || ZM_MYSQL_DATADIR="$ZIMBRA_ROOT/db/data"

if [ ! -d $ZM_MYSQL_DATADIR/mysql ]; then
    echo "$0: need to initialize mysql database" >&2
    /usr/bin/mysql_install_db \
        --defaults-file=$ZIMBRA_ROOT/conf/my.cnf \
        --datadir=$ZM_MYSQL_DATADIR \
        --user=zimbra
else
    echo "$0: mysql already initialized" >&2
fi
