#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later

## copy over generic makefile includes
repo_build_mk() {
    for i in $* ; do
        cp build.mk ../pkg/$i
        cp version.mk ../pkg/$i
    done
}

ANT_IVY_TARGET_REPOS="
    zm-zcs-lib
    zm-ldap-utilities
    zm-ldap-utils-store
    zm-taglib
"

for i in $ANT_IVY_TARGET_REPOS ; do
    cp ant-global.xml ivysettings.xml ../pkg/$i
done

## copy over elementary debian files
repo_debian_base() {
    repo_build_mk "$@"
    for i in $* ; do
        mkdir -p ../pkg/$i/debian/source
        cp debian/source/format ../pkg/$i/debian/source
        cp debian/compat ../pkg/$i/debian
    done
}

## copy over debian files for auto-versioned packages
repo_debian_autover() {
    repo_debian_base "$@"
    for i in $* ; do
        mkdir -p ../pkg/$i/debian
        cp debian/changelog.in ../pkg/$i/debian
        cp debian/rules ../pkg/$i/debian
    done
}

## auto-versioned packages with ivy
repo_ivy_debian_autover() {
    repo_debian_autover "$@"
    repo_ant_ivy "$@"
}

##

repo_build_mk \
    java-html-sanitizer-release-20190610.1 \
    ical4j-0.9.16-patched \
    nekohtml-1.9.13 \
    antisamy \
    zm-charset \
    zm-ldap-utilities \
    zm-launcher \
    zm-ldap-utils-store \
    zm-taglib \
    zm-core-utils \

