#!/bin/bash

BUILD_MK_TARGET_REPOS="
    java-html-sanitizer-release-20190610.1
    ical4j-0.9.16-patched
    nekohtml-1.9.13
    antisamy
    zm-charset
"

for i in $BUILD_MK_TARGET_REPOS ; do
    cp build.mk ../pkg/$i
done

ANT_IVY_TARGET_REPOS="
    zm-zcs-lib
    zm-ldap-utilities
"

for i in $ANT_IVY_TARGET_REPOS ; do
    cp ant-global.xml ivysettings.xml ../pkg/$i
done
