#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) Enrico Weigelt, metux IT consult <info@metux.net>

## copy over generic makefile includes
repo_build_mk() {
    for i in $* ; do
        cp build.mk ../pkg/$i
        cp version.mk ../pkg/$i
    done
}

## copy global ant/ivy build scripts
repo_ant_ivy() {
    for i in $* ; do
        cp ant-global.xml ../pkg/$i
        cp ivysettings.xml ../pkg/$i
    done
}

## copy over elementary debian files
repo_debian_base() {
    repo_build_mk "$@"
    for i in $* ; do
        mkdir -p ../pkg/$i/debian/source
        cp debian/source/format ../pkg/$i/debian/source
        cp debian/compat ../pkg/$i/debian
    done
}

## copy over debian files for auto-versioned packages
repo_debian_autover() {
    repo_debian_base "$@"
    for i in $* ; do
        mkdir -p ../pkg/$i/debian
        cp debian/changelog.in ../pkg/$i/debian
        cp debian/rules ../pkg/$i/debian
    done
}

## auto-versioned packages with ivy
repo_ivy_debian_autover() {
    repo_debian_autover "$@"
    repo_ant_ivy "$@"
}

##

repo_debian_base \
    java-html-sanitizer-release-20190610.1 \
    ical4j-0.9.16-patched \
    ant-1.7.0-ziputil-patched \
    ant-tar-patched \
    antisamy \

repo_debian_autover \
    junixsocket \
    nekohtml-1.9.13 \
    zm-db-conf \
    zm-dnscache \
    zm-freshclam \
    zm-help \
    ical4j-0.9.16-patched \
    zm-jetty-conf \
    zm-jython \
    zm-launcher \
    zm-mailbox \
    zm-mta \
    zm-nginx-conf \
    zm-postfix \
    zm-core-utils \
    zm-admin-help-common \
    zm-amavis \
    zm-aspell \
    zm-webclient-portal-example \
    zm-licenses \
    zm-downloads

repo_ivy_debian_autover \
    zm-admin-ajax \
    zm-admin-console \
    zm-ajax \
    zm-bulkprovision-admin-zimlet \
    zm-bulkprovision-store \
    zm-certificate-manager-admin-zimlet \
    zm-certificate-manager-store \
    zm-charset \
    zm-clam-scanner-store \
    zm-clientuploader-admin-zimlet \
    zm-clientuploader-store \
    zm-gql \
    zm-helptooltip-zimlet \
    zm-ldap-utilities \
    zm-ldap-utils-store \
    zm-nginx-lookup-store \
    zm-oauth-social \
    zm-openid-consumer-store \
    zm-proxy-config-admin-zimlet \
    zm-ssdb-ephemeral-store \
    zm-taglib \
    zm-versioncheck-admin-zimlet \
    zm-versioncheck-store \
    zm-viewmail-admin-zimlet \
    zm-web-client \
    zm-zcs-lib \
    zm-zimlets \
    zm-migration-tools \
    zm-timezones
