FROM zimbra/zm-base-os:devcore-ubuntu-20.04

ARG BUILD_UID
ARG BUILD_GID
ARG DOCKER_GID

USER root

# create the docker group
RUN groupadd -g ${DOCKER_GID} docker

# fix up the build user
RUN groupmod -g ${BUILD_GID} build
RUN usermod -u ${BUILD_UID} -g ${BUILD_GID} build
RUN chown -R build:build /home/build
RUN usermod -a -G docker build

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        mc rsync aptitude

RUN echo "deb file:/aptrepo/ focal contrib" >> /etc/apt/sources.list
COPY files/apt-repo.pub /

RUN apt-key add /apt-repo.pub

#RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 9BE6ED79

#USER build
